import type { ComponentDefinition, PortSpec } from '../types/component';
import { bool, choice, defineComponent, num } from './_shared/params';

const CALLER_OUT: PortSpec['out'] = [
    {
        id: 'out',
        protocols: [
            'http',
            'grpc',
            'sql',
            'nosql',
            'redis',
            'search',
            'olap',
            'kafka',
            'amqp',
            'sqs',
            's3',
            'internal',
        ],
        role: 'call',
    },
    { id: 'telemetry', protocols: ['telemetry'], role: 'observe' },
];

const SERVER_IN: PortSpec['in'] = [{ id: 'in', protocols: ['http', 'grpc', 'ws', 'internal'], role: 'serve' }];

const service = defineComponent({
    id: 'service',
    group: 'compute',
    shape: 'node',
    wave: 'mvp',
    icon: 'sd-service',
    ports: { in: SERVER_IN, out: CALLER_OUT },
    defaultParams: {
        runtime: 'go',
        instances: 3,
        autoscale: true,
        autoscaleMax: 20,
        autoscaleTargetUtilization: 0.65,
        azSpread: 3,
        serviceTimeMs: 20,
        serviceTimeSigma: 0.6,
        concurrencyPerInstance: 200,
        cpuCores: 4,
        memoryGb: 8,
        networkMbps: 1000,
        timeoutMs: 1000,
        queueLimit: 1000,
        callMode: 'sequential',
        logLinesPerRequest: 4,
        logBytesPerLine: 400,
        availability: 0.999,
        costPerInstanceHour: 0.17,
    },
    paramSchema: {
        runtime: choice('performance', ['jvm', 'go', 'node', 'python', 'dotnet']),
        instances: num('scale', { min: 1, max: 10000, realistic: { min: 1, max: 500 } }),
        autoscale: bool('scale'),
        autoscaleMax: num('scale', { min: 1, max: 10000 }),
        autoscaleTargetUtilization: num('scale', { min: 0.1, max: 0.95, step: 0.05 }),
        azSpread: num('scale', { min: 1, max: 6 }),
        serviceTimeMs: num('performance', { unitKey: 'ms', min: 0.1, max: 60000, realistic: { min: 1, max: 500 } }),
        serviceTimeSigma: num('performance', { min: 0.1, max: 2, step: 0.1 }),
        concurrencyPerInstance: num('capacity', { min: 1, max: 100000 }),
        cpuCores: num('capacity', { min: 0.25, max: 192, step: 0.25 }),
        memoryGb: num('capacity', { unitKey: 'gb', min: 0.125, max: 1024 }),
        networkMbps: num('capacity', { unitKey: 'mbps', min: 10, max: 100000 }),
        timeoutMs: num('behaviour', { unitKey: 'ms', min: 1, max: 300000 }),
        queueLimit: num('behaviour', { min: 0, max: 1000000 }),
        callMode: choice('behaviour', ['sequential', 'parallel']),
        logLinesPerRequest: num('data', { min: 0, max: 1000 }),
        logBytesPerLine: num('data', { unitKey: 'bytes', min: 10, max: 100000 }),
        availability: num('reliability', { min: 0.9, max: 0.99999, step: 0.0001 }),
        costPerInstanceHour: num('cost', { unitKey: 'usd', min: 0, max: 1000, step: 0.001 }),
    },
    helpId: 'service',
});

const monolith = defineComponent({
    id: 'monolith',
    group: 'compute',
    shape: 'node',
    wave: 'mvp',
    icon: 'sd-monolith',
    ports: { in: SERVER_IN, out: CALLER_OUT },
    defaultParams: {
        runtime: 'jvm',
        instances: 4,
        azSpread: 2,
        moduleCount: 12,
        serviceTimeMs: 45,
        serviceTimeSigma: 0.9,
        concurrencyPerInstance: 200,
        cpuCores: 8,
        memoryGb: 32,
        sharedDbConnections: 50,
        timeoutMs: 3000,
        queueLimit: 500,
        startupSec: 90,
        logLinesPerRequest: 8,
        logBytesPerLine: 500,
        availability: 0.995,
        costPerInstanceHour: 0.68,
    },
    paramSchema: {
        runtime: choice('performance', ['jvm', 'go', 'node', 'python', 'dotnet']),
        instances: num('scale', { min: 1, max: 500 }),
        azSpread: num('scale', { min: 1, max: 6 }),
        moduleCount: num('scale', { min: 1, max: 200 }),
        serviceTimeMs: num('performance', { unitKey: 'ms', min: 1, max: 60000 }),
        serviceTimeSigma: num('performance', { min: 0.1, max: 2, step: 0.1 }),
        concurrencyPerInstance: num('capacity', { min: 1, max: 10000 }),
        cpuCores: num('capacity', { min: 1, max: 192 }),
        memoryGb: num('capacity', { unitKey: 'gb', min: 1, max: 1024 }),
        sharedDbConnections: num('capacity', { min: 1, max: 5000 }),
        timeoutMs: num('behaviour', { unitKey: 'ms', min: 1, max: 300000 }),
        queueLimit: num('behaviour', { min: 0, max: 1000000 }),
        startupSec: num('behaviour', { unitKey: 'sec', min: 1, max: 3600 }),
        logLinesPerRequest: num('data', { min: 0, max: 1000 }),
        logBytesPerLine: num('data', { unitKey: 'bytes', min: 10, max: 100000 }),
        availability: num('reliability', { min: 0.9, max: 0.99999, step: 0.0001 }),
        costPerInstanceHour: num('cost', { unitKey: 'usd', min: 0, max: 1000, step: 0.001 }),
    },
    helpId: 'monolith',
});

const serverless = defineComponent({
    id: 'serverless',
    group: 'compute',
    shape: 'node',
    wave: 'mvp',
    icon: 'sd-serverless',
    ports: { in: SERVER_IN, out: CALLER_OUT },
    defaultParams: {
        memoryMb: 512,
        serviceTimeMs: 80,
        serviceTimeSigma: 0.8,
        coldStartMs: 400,
        provisionedConcurrency: 0,
        maxConcurrency: 1000,
        maxDurationSec: 900,
        timeoutMs: 30000,
        logLinesPerRequest: 3,
        logBytesPerLine: 400,
        costPerGbSecond: 0.0000166667,
        costPerMillionInvocations: 0.2,
    },
    paramSchema: {
        memoryMb: num('capacity', { unitKey: 'mb', min: 128, max: 10240, step: 64 }),
        serviceTimeMs: num('performance', { unitKey: 'ms', min: 1, max: 900000 }),
        serviceTimeSigma: num('performance', { min: 0.1, max: 2, step: 0.1 }),
        coldStartMs: num('performance', { unitKey: 'ms', min: 0, max: 10000 }),
        provisionedConcurrency: num('scale', { min: 0, max: 10000 }),
        maxConcurrency: num('capacity', { min: 1, max: 100000 }),
        maxDurationSec: num('behaviour', { unitKey: 'sec', min: 1, max: 900 }),
        timeoutMs: num('behaviour', { unitKey: 'ms', min: 1, max: 900000 }),
        logLinesPerRequest: num('data', { min: 0, max: 1000 }),
        logBytesPerLine: num('data', { unitKey: 'bytes', min: 10, max: 100000 }),
        costPerGbSecond: num('cost', { unitKey: 'usd', min: 0, max: 1, step: 0.0000001 }),
        costPerMillionInvocations: num('cost', { unitKey: 'usd', min: 0, max: 100, step: 0.01 }),
    },
    helpId: 'serverless',
});

const worker = defineComponent({
    id: 'worker',
    group: 'compute',
    shape: 'node',
    wave: 'mvp',
    icon: 'sd-worker',
    ports: {
        in: [{ id: 'in', protocols: ['kafka', 'amqp', 'sqs', 'internal'], role: 'consume' }],
        out: CALLER_OUT,
    },
    defaultParams: {
        instances: 4,
        concurrency: 16,
        processingTimeMs: 120,
        prefetch: 32,
        batchSize: 1,
        retries: 3,
        dlqEnabled: true,
        idempotent: true,
        cpuCores: 2,
        memoryGb: 4,
        logLinesPerRequest: 2,
        logBytesPerLine: 400,
        costPerInstanceHour: 0.09,
    },
    paramSchema: {
        instances: num('scale', { min: 1, max: 5000 }),
        concurrency: num('capacity', { min: 1, max: 10000 }),
        processingTimeMs: num('performance', { unitKey: 'ms', min: 1, max: 600000 }),
        prefetch: num('behaviour', { min: 1, max: 10000 }),
        batchSize: num('behaviour', { min: 1, max: 10000 }),
        retries: num('behaviour', { min: 0, max: 20 }),
        dlqEnabled: bool('reliability'),
        idempotent: bool('reliability'),
        cpuCores: num('capacity', { min: 0.25, max: 192, step: 0.25 }),
        memoryGb: num('capacity', { unitKey: 'gb', min: 0.125, max: 1024 }),
        logLinesPerRequest: num('data', { min: 0, max: 1000 }),
        logBytesPerLine: num('data', { unitKey: 'bytes', min: 10, max: 100000 }),
        costPerInstanceHour: num('cost', { unitKey: 'usd', min: 0, max: 1000, step: 0.001 }),
    },
    helpId: 'worker',
});

export const computeComponents: ComponentDefinition[] = [
    service,
    monolith,
    serverless,
    worker,
] as unknown as ComponentDefinition[];
