import type { ComponentDefinition } from '../types/component';
import { bool, choice, defineComponent, num } from './_shared/params';

const kafka = defineComponent({
    id: 'kafka',
    group: 'messaging',
    shape: 'node',
    wave: 'mvp',
    icon: 'sd-log-stream',
    ports: {
        in: [{ id: 'produce', protocols: ['kafka'], role: 'serve' }],
        out: [{ id: 'consume', protocols: ['kafka'], role: 'emit' }],
    },
    defaultParams: {
        brokers: 3,
        topics: 20,
        partitions: 12,
        replicationFactor: 3,
        minInsync: 2,
        acks: 'all',
        messageSizeKb: 4,
        batchMs: 10,
        compression: 'lz4',
        retentionHours: 168,
        diskGbPerBroker: 2000,
        throughputMbsPerBroker: 250,
        produceLatencyMs: 5,
        consumerGroups: 4,
        consumersPerGroup: 6,
        orderingScope: 'per-partition',
        availability: 0.9995,
        costPerInstanceHour: 0.45,
        costPerGbMonth: 0.1,
    },
    paramSchema: {
        brokers: num('topology', { min: 1, max: 500, realistic: { min: 3, max: 30 } }),
        topics: num('topology', { min: 1, max: 10000 }),
        partitions: num('capacity', { min: 1, max: 10000, realistic: { min: 3, max: 200 } }),
        replicationFactor: num('reliability', { min: 1, max: 9, realistic: { min: 2, max: 3 } }),
        minInsync: num('reliability', { min: 1, max: 9 }),
        acks: choice('reliability', ['none', 'leader', 'all']),
        messageSizeKb: num('data', { unitKey: 'kb', min: 0.05, max: 10240, step: 0.05 }),
        batchMs: num('behaviour', { unitKey: 'ms', min: 0, max: 10000 }),
        compression: choice('data', ['none', 'gzip', 'snappy', 'lz4', 'zstd']),
        retentionHours: num('data', { min: 1, max: 8760, realistic: { min: 24, max: 720 } }),
        diskGbPerBroker: num('capacity', { unitKey: 'gb', min: 10, max: 500000 }),
        throughputMbsPerBroker: num('capacity', { min: 1, max: 10000, realistic: { min: 100, max: 500 } }),
        produceLatencyMs: num('performance', { unitKey: 'ms', min: 0.1, max: 10000, step: 0.1 }),
        consumerGroups: num('scale', { min: 0, max: 1000 }),
        consumersPerGroup: num('scale', { min: 1, max: 10000 }),
        orderingScope: choice('consistency', ['none', 'per-key', 'per-partition', 'global']),
        availability: num('reliability', { min: 0.9, max: 0.99999, step: 0.0001 }),
        costPerInstanceHour: num('cost', { unitKey: 'usd', min: 0, max: 1000, step: 0.001 }),
        costPerGbMonth: num('cost', { unitKey: 'usd', min: 0, max: 10, step: 0.001 }),
    },
    helpId: 'kafka',
});

const rabbitmq = defineComponent({
    id: 'rabbitmq',
    group: 'messaging',
    shape: 'node',
    wave: 'mvp',
    icon: 'sd-queue',
    ports: {
        in: [{ id: 'in', protocols: ['amqp'], role: 'serve' }],
        out: [
            { id: 'consume', protocols: ['amqp'], role: 'emit' },
            { id: 'dlq', protocols: ['amqp'], role: 'emit' },
        ],
    },
    defaultParams: {
        nodes: 3,
        queues: 20,
        quorumQueues: true,
        throughputPerQueue: 20000,
        prefetch: 32,
        ackMode: 'manual',
        messageSizeKb: 2,
        maxQueueDepth: 100000,
        lazyQueues: false,
        ttlSec: 3600,
        priorityLevels: 1,
        dlqEnabled: true,
        publishLatencyMs: 2,
        memoryGb: 16,
        diskGb: 200,
        availability: 0.999,
        costPerInstanceHour: 0.25,
    },
    paramSchema: {
        nodes: num('topology', { min: 1, max: 100, realistic: { min: 3, max: 7 } }),
        queues: num('topology', { min: 1, max: 100000 }),
        quorumQueues: bool('reliability'),
        throughputPerQueue: num('capacity', { unitKey: 'rps', min: 100, max: 1000000, realistic: { min: 20000, max: 50000 } }),
        prefetch: num('behaviour', { min: 1, max: 10000 }),
        ackMode: choice('behaviour', ['auto', 'manual']),
        messageSizeKb: num('data', { unitKey: 'kb', min: 0.05, max: 10240, step: 0.05 }),
        maxQueueDepth: num('capacity', { min: 100, max: 100000000 }),
        lazyQueues: bool('behaviour'),
        ttlSec: num('behaviour', { unitKey: 'sec', min: 0, max: 604800 }),
        priorityLevels: num('behaviour', { min: 1, max: 10 }),
        dlqEnabled: bool('reliability'),
        publishLatencyMs: num('performance', { unitKey: 'ms', min: 0.1, max: 10000, step: 0.1 }),
        memoryGb: num('capacity', { unitKey: 'gb', min: 0.5, max: 1024, step: 0.5 }),
        diskGb: num('capacity', { unitKey: 'gb', min: 1, max: 100000 }),
        availability: num('reliability', { min: 0.9, max: 0.99999, step: 0.0001 }),
        costPerInstanceHour: num('cost', { unitKey: 'usd', min: 0, max: 1000, step: 0.001 }),
    },
    helpId: 'rabbitmq',
});

const sqs = defineComponent({
    id: 'sqs',
    group: 'messaging',
    shape: 'node',
    wave: 'mvp',
    icon: 'sd-queue-managed',
    ports: {
        in: [{ id: 'in', protocols: ['sqs'], role: 'serve' }],
        out: [
            { id: 'consume', protocols: ['sqs'], role: 'emit' },
            { id: 'dlq', protocols: ['sqs'], role: 'emit' },
        ],
    },
    defaultParams: {
        queueType: 'standard',
        visibilityTimeoutSec: 30,
        maxReceiveCount: 5,
        dlqEnabled: true,
        batchSize: 10,
        messageSizeKb: 8,
        retentionHours: 96,
        longPollingSec: 20,
        delaySec: 0,
        fifoThroughputLimit: 3000,
        maxInflight: 120000,
        publishLatencyMs: 10,
        availability: 0.9999,
        costPerMillionRequests: 0.4,
    },
    paramSchema: {
        queueType: choice('behaviour', ['standard', 'fifo']),
        visibilityTimeoutSec: num('behaviour', { unitKey: 'sec', min: 0, max: 43200 }),
        maxReceiveCount: num('reliability', { min: 1, max: 1000 }),
        dlqEnabled: bool('reliability'),
        batchSize: num('behaviour', { min: 1, max: 10 }),
        messageSizeKb: num('data', { unitKey: 'kb', min: 0.05, max: 256, step: 0.05 }),
        retentionHours: num('data', { min: 1, max: 336 }),
        longPollingSec: num('behaviour', { unitKey: 'sec', min: 0, max: 20 }),
        delaySec: num('behaviour', { unitKey: 'sec', min: 0, max: 900 }),
        fifoThroughputLimit: num('capacity', { unitKey: 'rps', min: 300, max: 70000 }),
        maxInflight: num('capacity', { min: 1000, max: 1000000 }),
        publishLatencyMs: num('performance', { unitKey: 'ms', min: 0.5, max: 10000, step: 0.5 }),
        availability: num('reliability', { min: 0.9, max: 0.99999, step: 0.0001 }),
        costPerMillionRequests: num('cost', { unitKey: 'usd', min: 0, max: 100, step: 0.01 }),
    },
    helpId: 'sqs',
});

const dlq = defineComponent({
    id: 'dlq',
    group: 'messaging',
    shape: 'node',
    wave: 'mvp',
    icon: 'sd-dlq',
    ports: {
        in: [{ id: 'in', protocols: ['kafka', 'amqp', 'sqs'], role: 'serve' }],
        out: [{ id: 'reprocess', protocols: ['kafka', 'amqp', 'sqs'], role: 'emit' }],
    },
    defaultParams: {
        maxRetries: 5,
        reprocessMode: 'manual',
        reprocessBatchSize: 50,
        redriveDelaySec: 300,
        alertThresholdMessages: 100,
        notifyOnArrival: true,
        maxDepth: 1000000,
        retentionHours: 336,
        messageSizeKb: 4,
        costPerMillionRequests: 0.4,
    },
    paramSchema: {
        maxRetries: num('reliability', { min: 0, max: 100 }),
        reprocessMode: choice('behaviour', ['manual', 'auto', 'scheduled']),
        reprocessBatchSize: num('behaviour', { min: 1, max: 10000 }),
        redriveDelaySec: num('behaviour', { unitKey: 'sec', min: 0, max: 86400 }),
        alertThresholdMessages: num('reliability', { min: 1, max: 10000000 }),
        notifyOnArrival: bool('reliability'),
        maxDepth: num('capacity', { min: 100, max: 1000000000 }),
        retentionHours: num('data', { min: 1, max: 8760 }),
        messageSizeKb: num('data', { unitKey: 'kb', min: 0.05, max: 10240, step: 0.05 }),
        costPerMillionRequests: num('cost', { unitKey: 'usd', min: 0, max: 100, step: 0.01 }),
    },
    helpId: 'dlq',
});

export const messagingComponents: ComponentDefinition[] = [
    kafka,
    rabbitmq,
    sqs,
    dlq,
] as unknown as ComponentDefinition[];
