import type { ComponentDefinition, PortSpec } from '../types/component';
import { bool, choice, defineComponent, num, text } from './_shared/params';

const NOSQL_PORTS: PortSpec = {
    in: [{ id: 'query', protocols: ['nosql'], role: 'serve' }],
    out: [
        { id: 'replication', protocols: ['nosql'], role: 'replicate' },
        { id: 'cdc', protocols: ['kafka'], role: 'emit' },
    ],
};

const CONSISTENCY_MODEL = [
    'linearizable',
    'sequential',
    'bounded-staleness',
    'read-your-writes',
    'monotonic',
    'eventual',
];

const REPLICATION_MODE = ['sync', 'semi-sync', 'async'];

const CONCURRENCY_CONTROL = ['none', 'optimistic', 'pessimistic', 'crdt'];

const CONFLICT_RESOLUTION = ['lww', 'vector-clock', 'crdt', 'single-writer-per-key', 'manual'];

const mongodb = defineComponent({
    id: 'mongodb',
    group: 'nosql',
    shape: 'node',
    wave: 'mvp',
    icon: 'sd-document',
    ports: NOSQL_PORTS,
    defaultParams: {
        replicaSetSize: 3,
        shardCount: 1,
        shardKey: 'userId',
        writeConcern: 'majority',
        readPreference: 'primary',
        documentSizeKb: 4,
        documentCount: 500000000,
        indexCount: 5,
        workingSetGb: 40,
        wiredTigerCacheGb: 32,
        storageGb: 3000,
        cpuCores: 16,
        maxConnections: 1000,
        readServiceMs: 0.5,
        writeServiceMs: 1.5,
        consistencyModel: 'read-your-writes',
        replicationMode: 'semi-sync',
        replicaLagMs: 100,
        quorumN: 3,
        quorumR: 1,
        quorumW: 2,
        concurrencyControl: 'optimistic',
        conflictResolution: 'single-writer-per-key',
        availability: 0.9995,
        costPerInstanceHour: 0.55,
        costPerGbMonth: 0.115,
    },
    paramSchema: {
        replicaSetSize: num('topology', { min: 1, max: 50, realistic: { min: 3, max: 7 } }),
        shardCount: num('topology', { min: 1, max: 4096 }),
        shardKey: text('topology'),
        writeConcern: choice('consistency', ['w1', 'majority', 'all']),
        readPreference: choice('consistency', ['primary', 'primary-preferred', 'secondary', 'nearest']),
        documentSizeKb: num('data', { unitKey: 'kb', min: 0.05, max: 16384, step: 0.05 }),
        documentCount: num('data', { min: 0, max: 1000000000000 }),
        indexCount: num('data', { min: 0, max: 64 }),
        workingSetGb: num('data', { unitKey: 'gb', min: 0.1, max: 100000, step: 0.1 }),
        wiredTigerCacheGb: num('capacity', { unitKey: 'gb', min: 0.25, max: 4096, step: 0.25 }),
        storageGb: num('capacity', { unitKey: 'gb', min: 1, max: 10000000 }),
        cpuCores: num('capacity', { min: 1, max: 192 }),
        maxConnections: num('capacity', { min: 10, max: 200000 }),
        readServiceMs: num('performance', { unitKey: 'ms', min: 0.05, max: 60000, step: 0.05 }),
        writeServiceMs: num('performance', { unitKey: 'ms', min: 0.05, max: 60000, step: 0.05 }),
        consistencyModel: choice('consistency', CONSISTENCY_MODEL),
        replicationMode: choice('consistency', REPLICATION_MODE),
        replicaLagMs: num('consistency', { unitKey: 'ms', min: 0, max: 600000, realistic: { min: 20, max: 2000 } }),
        quorumN: num('consistency', { min: 1, max: 50 }),
        quorumR: num('consistency', { min: 1, max: 50 }),
        quorumW: num('consistency', { min: 1, max: 50 }),
        concurrencyControl: choice('consistency', CONCURRENCY_CONTROL),
        conflictResolution: choice('consistency', CONFLICT_RESOLUTION),
        availability: num('reliability', { min: 0.9, max: 0.99999, step: 0.0001 }),
        costPerInstanceHour: num('cost', { unitKey: 'usd', min: 0, max: 1000, step: 0.001 }),
        costPerGbMonth: num('cost', { unitKey: 'usd', min: 0, max: 10, step: 0.001 }),
    },
    helpId: 'mongodb',
});

const cassandra = defineComponent({
    id: 'cassandra',
    group: 'nosql',
    shape: 'node',
    wave: 'mvp',
    icon: 'sd-wide-column',
    ports: NOSQL_PORTS,
    defaultParams: {
        nodes: 6,
        replicationFactor: 3,
        partitionKey: 'userId',
        partitionSizeMb: 64,
        rowSizeBytes: 200,
        rowCount: 5000000000,
        compactionStrategy: 'stcs',
        compressionRatio: 3,
        tombstoneRatio: 0.05,
        writeAmplification: 4,
        storageGbPerNode: 2000,
        cpuCores: 16,
        maxOpsPerSecPerNode: 20000,
        readServiceMs: 1.5,
        writeServiceMs: 0.3,
        hintedHandoff: true,
        consistencyModel: 'eventual',
        replicationMode: 'async',
        replicaLagMs: 30,
        quorumN: 3,
        quorumR: 2,
        quorumW: 2,
        concurrencyControl: 'none',
        conflictResolution: 'lww',
        availability: 0.9995,
        costPerInstanceHour: 0.5,
        costPerGbMonth: 0.08,
    },
    paramSchema: {
        nodes: num('topology', { min: 1, max: 1000, realistic: { min: 3, max: 100 } }),
        replicationFactor: num('topology', { min: 1, max: 9, realistic: { min: 2, max: 3 } }),
        partitionKey: text('topology'),
        partitionSizeMb: num('data', { unitKey: 'mb', min: 0.1, max: 10000, step: 0.1, realistic: { min: 1, max: 100 } }),
        rowSizeBytes: num('data', { unitKey: 'bytes', min: 10, max: 1000000 }),
        rowCount: num('data', { min: 0, max: 1000000000000 }),
        compactionStrategy: choice('data', ['stcs', 'lcs', 'twcs']),
        compressionRatio: num('data', { min: 1, max: 30, step: 0.1 }),
        tombstoneRatio: num('data', { min: 0, max: 1, step: 0.01 }),
        writeAmplification: num('capacity', { min: 1, max: 50, step: 0.5 }),
        storageGbPerNode: num('capacity', { unitKey: 'gb', min: 10, max: 200000 }),
        cpuCores: num('capacity', { min: 1, max: 192 }),
        maxOpsPerSecPerNode: num('capacity', { unitKey: 'rps', min: 100, max: 1000000, realistic: { min: 5000, max: 50000 } }),
        readServiceMs: num('performance', { unitKey: 'ms', min: 0.05, max: 60000, step: 0.05 }),
        writeServiceMs: num('performance', { unitKey: 'ms', min: 0.05, max: 60000, step: 0.05 }),
        hintedHandoff: bool('reliability'),
        consistencyModel: choice('consistency', CONSISTENCY_MODEL),
        replicationMode: choice('consistency', REPLICATION_MODE),
        replicaLagMs: num('consistency', { unitKey: 'ms', min: 0, max: 600000, realistic: { min: 5, max: 500 } }),
        quorumN: num('consistency', { min: 1, max: 50 }),
        quorumR: num('consistency', { min: 1, max: 50 }),
        quorumW: num('consistency', { min: 1, max: 50 }),
        concurrencyControl: choice('consistency', CONCURRENCY_CONTROL),
        conflictResolution: choice('consistency', CONFLICT_RESOLUTION),
        availability: num('reliability', { min: 0.9, max: 0.99999, step: 0.0001 }),
        costPerInstanceHour: num('cost', { unitKey: 'usd', min: 0, max: 1000, step: 0.001 }),
        costPerGbMonth: num('cost', { unitKey: 'usd', min: 0, max: 10, step: 0.001 }),
    },
    helpId: 'cassandra',
});

const dynamodb = defineComponent({
    id: 'dynamodb',
    group: 'nosql',
    shape: 'node',
    wave: 'mvp',
    icon: 'sd-keyvalue',
    ports: NOSQL_PORTS,
    defaultParams: {
        capacityMode: 'on-demand',
        rcu: 20000,
        wcu: 5000,
        maxRcuPerPartition: 3000,
        maxWcuPerPartition: 1000,
        partitionKey: 'userId',
        hotPartitionShare: 0.1,
        itemSizeKb: 2,
        itemCount: 1000000000,
        gsiCount: 2,
        ttlEnabled: true,
        streams: true,
        readServiceMs: 4,
        writeServiceMs: 8,
        consistencyModel: 'eventual',
        replicationMode: 'async',
        replicaLagMs: 20,
        concurrencyControl: 'optimistic',
        conflictResolution: 'lww',
        availability: 0.9999,
        costPerMillionReads: 0.125,
        costPerMillionWrites: 0.625,
        costPerGbMonth: 0.25,
    },
    paramSchema: {
        capacityMode: choice('capacity', ['provisioned', 'on-demand']),
        rcu: num('capacity', { min: 0, max: 40000000 }),
        wcu: num('capacity', { min: 0, max: 40000000 }),
        maxRcuPerPartition: num('capacity', { min: 100, max: 100000 }),
        maxWcuPerPartition: num('capacity', { min: 100, max: 100000 }),
        partitionKey: text('topology'),
        hotPartitionShare: num('behaviour', { min: 0, max: 1, step: 0.01 }),
        itemSizeKb: num('data', { unitKey: 'kb', min: 0.1, max: 400, step: 0.1 }),
        itemCount: num('data', { min: 0, max: 1000000000000 }),
        gsiCount: num('data', { min: 0, max: 20 }),
        ttlEnabled: bool('data'),
        streams: bool('data'),
        readServiceMs: num('performance', { unitKey: 'ms', min: 0.5, max: 60000, step: 0.5 }),
        writeServiceMs: num('performance', { unitKey: 'ms', min: 0.5, max: 60000, step: 0.5 }),
        consistencyModel: choice('consistency', CONSISTENCY_MODEL),
        replicationMode: choice('consistency', REPLICATION_MODE),
        replicaLagMs: num('consistency', { unitKey: 'ms', min: 0, max: 600000, realistic: { min: 5, max: 500 } }),
        concurrencyControl: choice('consistency', CONCURRENCY_CONTROL),
        conflictResolution: choice('consistency', CONFLICT_RESOLUTION),
        availability: num('reliability', { min: 0.9, max: 0.99999, step: 0.0001 }),
        costPerMillionReads: num('cost', { unitKey: 'usd', min: 0, max: 100, step: 0.001 }),
        costPerMillionWrites: num('cost', { unitKey: 'usd', min: 0, max: 100, step: 0.001 }),
        costPerGbMonth: num('cost', { unitKey: 'usd', min: 0, max: 10, step: 0.001 }),
    },
    helpId: 'dynamodb',
});

export const nosqlComponents: ComponentDefinition[] = [
    mongodb,
    cassandra,
    dynamodb,
] as unknown as ComponentDefinition[];
